Komposed yml 걷어내고 기타 사소한 코드 수정
femiwiki/kubernetes pull request #2
Opened 2020-01-06 03:55 UTC by love-adela

2020-01-06 09:14 UTC, lens0021 commented
리베이스 하시면서 새 yaml파일들은 [리드미](https://github.com/femiwiki/kubernetes/blob/master/README.md)에 적힌대로`service/` 안으로 옮겨주시면 좋을거 같아요

2020-01-06 21:42 UTC, miriryu commented
재리뷰 부탁합니당

2020-01-07 14:03 UTC, simnalamburt requested changes
```
apiVersion: v1
kind: Namespace
metadata:
  name: femiwiki
```

네임스페이스 안에 모두 넣으면 좋을것같습니다. 위와 같은 리소스를 만드신 뒤, 모든 파일 metadata 밑에 `namespace: femiwiki` 이정도 추가되면 어떨까 싶네요.

그리고 파일이 좀 너무 여러개로 쪼개져있는데, caddy는 한 yaml로, mysql도 한 yaml로, fastcgi도 한 yaml로 이런식으로 연관있는것들은 뭉치면 좋을것같아요. 여러 YAML 하나로 붙이는 문법은 https://github.com/upnl/kubernetes/blob/7d3934313/service/homepage.yml#L5 를 참고해주세요.

그리고 PVC 사이즈가 지금 placeholder로 100MiB로 되어있는데, 서버 액세스권한 갖고계신분중 시간되시는 분께서 지금 서버에서 각 PVC 안에 들어갈 데이터 용량이 어느정도 되는지 재서, 각 PVC들 용량 확정지어주시면 좋을것같습니다.

2020-01-07 14:03 UTC, simnalamburt commented on service/fastcgi-claim0-persistentvolumeclaim.yaml
> +  name: fastcgi-claim0
이 PVC 삭제해주시고, 이 PVC가 등장하는곳도 모두 지워주세요. 이게 `secret.php` 설정파일 넣으려고 있던 마운트인데 쿠버네티스에선 이거 대신 `Secret`이라는 리소스를 써야합니다.

https://kubernetes.io/docs/concepts/configuration/secret/

이건 지금 페미위키에서 `secret.php`가 어떻게 쓰이고있는지 아셔야 작성하실 수 있을것같은데, 낙엽님한테 여쭤가며 하시거나 못하시겠으면 제가할테니 PR 본문에 TODO로 남겨주세요.

2020-01-07 14:03 UTC, simnalamburt commented on service/http-claim0-persistentvolumeclaim.yaml
> +  name: http-claim0
`fastcgi-claim0`와 마찬가지로, 설정파일인 Caddyfile 주입하려고 마운트했던 디렉토리이고, ConfigMap으로 고치거나 아예 컨테이너 이미지 안에 embed해야합니다.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/

낙엽님한테 여쭤가며 해주시거나, TODO로 남겨주세요.

2020-01-07 14:03 UTC, simnalamburt commented on service/memcached-deployment.yaml
> +      restartPolicy: Always
`restartPolicy: Always`는 기본값이므로 삭제해주세요
```suggestion
```

2020-01-07 14:03 UTC, simnalamburt commented on service/fastcgi-deployment.yaml
> +  replicas: 1
`replicas: 1` 기본값이므로 삭제해주세요
```suggestion
```

2020-01-07 14:03 UTC, simnalamburt commented on service/fastcgi-deployment.yaml
> +      restartPolicy: Always
기본값이니 삭제부탁드립니다
```suggestion
```

2020-01-07 14:03 UTC, simnalamburt commented on service/memcached-deployment.yaml
> +  replicas: 1
```suggestion
```

기본값이므로 삭제

2020-01-07 14:03 UTC, simnalamburt commented on service/fastcgi-deployment.yaml
> +    type: Recreate
이 두 라인 지워주세요. 그러면 strategy가 기본값인 RollingUpdate로 폴백되는데, 롤링업데이트가 원하는 동작입니다.

2020-01-07 14:03 UTC, simnalamburt commented on service/http-pod.yaml
> +    - containerPort: 443
```suggestion
```

이제 TLS termination을 pod에서 하는게 아니라 Kubernetes traefik ingress controller에서 할거라, 80번 포트만 노출해야합니다. 마찬가지로 Caddyfile도 80번 포트만 쓰도록 고쳐야합니다. 이건 맥락을 모르셔서 좀 힘드실것같은데, 못하시겠으면 그냥 TODO로 남겨주세요.

2020-01-07 14:03 UTC, simnalamburt commented on service/http-service.yaml
> +    targetPort: 443
위와 마찬가지입니다. 80번 포트만 써야합니다. 세 라인 삭제해주세요

2020-01-07 14:03 UTC, simnalamburt commented on service/mysql-deployment.yaml
> +  replicas: 1
```suggestion
```
기본값으로 삭제해주세요

2020-01-07 14:03 UTC, simnalamburt commented on service/mysql-deployment.yaml
> +kind: Deployment
MySQL은 Deployment가 아니라 StatefulSet으로 띄워야할것같습니다. https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/

https://github.com/upnl/kubernetes/blob/7d3934313acb9a2c5d457f932e710ca92ed4a6c1/service/homepage.yml#L20 이거 참고해주세요

2020-01-07 14:03 UTC, simnalamburt commented on service/mysql-deployment.yaml
> +    type: Recreate
노파심에 말씀드리지만 DB는 롤링업데이트하면 안되므로 Recreate가 맞습니다.

2020-01-07 14:03 UTC, simnalamburt commented on service/mysql-deployment.yaml
> +        - name: MYSQL_PASSWORD
```suggestion
        # NOTE: 개발용으로만 사용되는 옵션이고 실제 프로덕션에서는 무시되는 옵션들임
        - name: MYSQL_PASSWORD
```

보고 놀랄수도 있는 사람들을 위해 주석 추가

2020-01-07 14:03 UTC, simnalamburt commented on service/mysql-deployment.yaml
> +
```suggestion
```

빈 뉴라인 삭제

2020-01-07 14:03 UTC, simnalamburt commented on service/parsoid-deployment.yaml
> +  replicas: 1
```suggestion
```

기본값이므로 삭제

2020-01-07 14:03 UTC, simnalamburt commented on service/parsoid-deployment.yaml
> +      restartPolicy: Always
```suggestion
```

기본값이므로 삭제

2020-01-27 14:54 UTC, lens0021 commented
> 그리고 PVC 사이즈가 지금 placeholder로 100MiB로 되어있는데, 서버 액세스권한 갖고계신분중 시간되시는 분께서 지금 서버에서 각 PVC 안에 들어갈 데이터 용량이 어느정도 되는지 재서, 각 PVC들 용량 확정지어주시면 좋을것같습니다.

```sh
$ docker system df -v
# 중략
Local Volumes space usage:

VOLUME NAME                                                        LINKS               SIZE
mediawiki_files                                                    2                   1.303GB
mediawiki_caddy                                                    1                   9.002kB
4f76c3dbf991ee665ba5a6169474ccddd8f5cc87d0d0bc0b1adbd502006f408a   1                   0B
mediawiki_l18n_cache                                               1                   206.2MB
abbc79047d7bc613ad1ecf3d6b5977d3492bef3a809a01da24f0a4ee5815f234   0                   36B
562889a87205c974d5f12b4746136eaeed5cc5969336c51afe5cceec0414c26d   1                   516B
a2e57b4d172fbc3b793de45339ecf9bf614b6a6ae41955df787f80aa22b21c8c   0                   516B
24ec6770781dd2ff6aceeb59d751214a6e767c6453cce5e18b748ea26732d27b   1                   36B
```

2020-02-13 09:02 UTC, simnalamburt requested changes
### TODO
- [x] 여러 YAML들 합치기
- [x] 서비스들 네임스페이스에 넣기
- [x] http Pod 대신 디플로이먼트로 띄우기
- [x] http Pod에 caddycerts 마운트 안해도됨
- [ ] 각 PVC 사이즈 확정하기
- [ ] mediawiki Caddyfile 고쳐서 HTTP만 서빙하게 만들기
- [ ] FastCGI에 넣을 secret.php을 Kubernetes 시크릿으로 관리하기 https://github.com/femiwiki/kubernetes/pull/2#discussion_r363753048
- [ ] FastCGI에 넣을 Caddy 설정파일을 ConfigMap으로 관리하기, 혹은 Caddy 자체가 필요 없을지도? https://github.com/femiwiki/kubernetes/pull/2#discussion_r363756022
- [ ] Kubernetes traefik ingress controller https://github.com/femiwiki/kubernetes/pull/2#discussion_r363758997
- [ ] MySQL 지금 deployment인데 statefulset으로 고치기 https://github.com/femiwiki/kubernetes/pull/2#discussion_r363759980
- [ ] RESTBase 붙이기

2020-02-13 12:50 UTC, simnalamburt commented
주석에 TODO들 달은채로 일단 머지하겠습니다

2020-02-13 12:50 UTC, simnalamburt approved these changes

2020-02-13 12:53 UTC, merged